#!/usr/bin/env python3
"""Render deterministic skill and research indexes."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from repository_model import (
    ROOT,
    build_skill_index,
    dump_json,
    load_json,
    load_packets,
    load_records,
)


def render_skill_markdown(index: dict) -> str:
    lines = [
        "# Reviewed skill index",
        "",
        "Generated by `scripts/render_indexes.py`. Do not edit by hand.",
        "",
        "Only `skill-index` is a bootstrap skill. Search should return compact",
        "summaries and load one selected skill at a time.",
        "",
        "| Domain | Skill | Load mode | Status | Summary |",
        "| --- | --- | --- | --- | --- |",
    ]
    for skill in index["skills"]:
        link = f"[{skill['name']}](../{skill['path']}/SKILL.md)"
        lines.append(
            f"| {skill['domain']} | {link} | {skill['load_mode']} | "
            f"{skill['status']} | {skill['summary']} |"
        )
    lines.extend(
        [
            "",
            "Machine consumers should use [skills.json](skills.json), which includes",
            "triggers, exclusions, declarative composition edges, review state, bundle",
            "digests, and per-file SHA-256 values. Composition metadata never causes",
            "another skill to be loaded or executed.",
            "",
        ]
    )
    return "\n".join(lines)


def render_research_markdown(root: Path = ROOT) -> str:
    packet_paths = sorted((root / "research" / "packets").glob("*.json"))
    packets = load_packets(root)
    path_by_id = {
        packet["id"]: path.relative_to(root / "research").as_posix()
        for path, packet in zip(packet_paths, packets)
    }
    used_by: dict[str, set[str]] = {}
    for record in load_records("skills", root):
        references = set(record.get("source_refs", []))
        review = load_json(root / record["review_path"])
        references.update(review.get("source_refs", []))
        for reference in references:
            used_by.setdefault(reference, set()).add(record["name"])
    lines = [
        "# Research and source index",
        "",
        "Generated by `scripts/render_indexes.py`. Do not edit by hand.",
        "",
        "Packets are bounded research rounds. They preserve exact sources and the",
        "decisions that affected the repository without storing raw search output.",
        "",
        "| Researched | Packet | Sources | Question |",
        "| --- | --- | ---: | --- |",
    ]
    for packet in packets:
        link = f"[{packet['id']}]({path_by_id[packet['id']]})"
        lines.append(
            f"| {packet['researched_at']} | {link} | {len(packet['sources'])} | "
            f"{packet['question']} |"
        )
    lines.extend(["", "## Sources", ""])
    for packet in packets:
        lines.extend(
            [
                f"### {packet['id']}",
                "",
                "| Source ID | Source | Disposition | Used by | Revision | License |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        for source in packet["sources"]:
            title = source["title"]
            if source["url"].startswith("https://"):
                title = f"[{title}]({source['url']})"
            reference = f"{packet['id']}:{source['id']}"
            consumers = ", ".join(sorted(used_by.get(reference, set()))) or "-"
            lines.append(
                f"| `{source['id']}` | {title} | {source['disposition']} | "
                f"{consumers} | `{source['revision']}` | {source['license']} |"
            )
        lines.append("")
    return "\n".join(lines)


def expected_outputs(root: Path = ROOT) -> dict[Path, str]:
    index = build_skill_index(root)
    return {
        root / "index" / "skills.json": dump_json(index),
        root / "index" / "README.md": render_skill_markdown(index),
        root / "research" / "README.md": render_research_markdown(root),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[str] = []
    for path, content in expected_outputs().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        for relative in stale:
            print(f"ERROR: generated file is stale: {relative}")
        return 1
    if args.check:
        print("generated indexes are current")
    else:
        print("rendered skill and research indexes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
